spring:
  application:
    name: PlayermarktEurekaServer
server:
  port: ${PORT:8761}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0