spring:
  application:
    name: playermarkt-service-b
server:
  port: 8976
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true