spring:
  application:
    name: playermarkt-service-a
feign:
  hystrix:
    enabled: true # This is required to use Hystrix with feign
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true